#!/usr/bin/env python3
"""Analyze the CSV generated by apps/reproduce_cube_smoke.c.

This diagnostic script intentionally uses only Python's standard library. It
does not alter the C implementation; it reads the smoke-run CSV and writes a
small aggregate summary for later inspection.
"""

import argparse
import csv
import math
import os
import sys


DEFAULT_INPUT = "data/output/cube_smoke_solution.csv"
DEFAULT_OUTPUT = "data/output/cube_smoke_error_summary.csv"


def parse_args():
    parser = argparse.ArgumentParser(
        description="Analyze the didactic cube smoke CSV generated by reproduce_cube_smoke."
    )
    parser.add_argument(
        "L",
        nargs="?",
        type=float,
        default=10.0,
        help="Cube side length used to classify interior/surface points. Default: 10.0",
    )
    parser.add_argument(
        "--input",
        default=DEFAULT_INPUT,
        help=f"Input CSV path. Default: {DEFAULT_INPUT}",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Summary CSV path. Default: {DEFAULT_OUTPUT}",
    )
    return parser.parse_args()


def read_rows(path):
    rows = []

    with open(path, newline="") as csv_file:
        reader = csv.DictReader(csv_file)
        required_columns = {"x", "y", "z", "V_eval", "V_exact", "abs_error"}
        missing_columns = required_columns.difference(reader.fieldnames or [])

        if missing_columns:
            missing = ", ".join(sorted(missing_columns))
            raise ValueError(f"input CSV is missing columns: {missing}")

        for line_number, row in enumerate(reader, start=2):
            try:
                rows.append(
                    {
                        "x": float(row["x"]),
                        "y": float(row["y"]),
                        "z": float(row["z"]),
                        "V_eval": float(row["V_eval"]),
                        "V_exact": float(row["V_exact"]),
                        "abs_error": float(row["abs_error"]),
                    }
                )
            except ValueError as exc:
                raise ValueError(f"invalid numeric value on line {line_number}") from exc

    return rows


def is_boundary_coordinate(value, L, tolerance):
    return abs(value) <= tolerance or abs(value - L) <= tolerance


def is_internal(row, L, tolerance):
    return (
        tolerance < row["x"] < L - tolerance
        and tolerance < row["y"] < L - tolerance
        and tolerance < row["z"] < L - tolerance
    )


def is_surface(row, L, tolerance):
    return (
        is_boundary_coordinate(row["x"], L, tolerance)
        or is_boundary_coordinate(row["y"], L, tolerance)
        or is_boundary_coordinate(row["z"], L, tolerance)
    )


def is_near_edge(row, L, tolerance):
    boundary_coordinates = 0

    for coordinate in (row["x"], row["y"], row["z"]):
        if is_boundary_coordinate(coordinate, L, tolerance):
            boundary_coordinates += 1

    return boundary_coordinates >= 2


def relative_discrete_error(rows):
    numerator = 0.0
    denominator = 0.0

    for row in rows:
        difference = row["V_eval"] - row["V_exact"]

        numerator += difference * difference
        denominator += row["V_exact"] * row["V_exact"]

    if denominator == 0.0:
        return None

    return math.sqrt(numerator / denominator)


def summarize(scope, rows):
    if not rows:
        return {
            "scope": scope,
            "point_count": 0,
            "max_abs_error": None,
            "mean_abs_error": None,
            "relative_discrete_error": None,
        }

    abs_errors = [row["abs_error"] for row in rows]

    return {
        "scope": scope,
        "point_count": len(rows),
        "max_abs_error": max(abs_errors),
        "mean_abs_error": sum(abs_errors) / len(abs_errors),
        "relative_discrete_error": relative_discrete_error(rows),
    }


def format_metric(value):
    if value is None:
        return "n/a"

    return f"{value:.17g}"


def write_summary(path, summaries):
    output_directory = os.path.dirname(path)

    if output_directory:
        os.makedirs(output_directory, exist_ok=True)

    with open(path, "w", newline="") as csv_file:
        fieldnames = [
            "scope",
            "point_count",
            "max_abs_error",
            "mean_abs_error",
            "relative_discrete_error",
        ]
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)

        writer.writeheader()
        for summary in summaries:
            writer.writerow(
                {
                    "scope": summary["scope"],
                    "point_count": summary["point_count"],
                    "max_abs_error": format_metric(summary["max_abs_error"]),
                    "mean_abs_error": format_metric(summary["mean_abs_error"]),
                    "relative_discrete_error": format_metric(
                        summary["relative_discrete_error"]
                    ),
                }
            )


def main():
    args = parse_args()

    if args.L <= 0.0:
        print("L must be positive.", file=sys.stderr)
        return 1

    tolerance = max(1.0e-12, abs(args.L) * 1.0e-12)

    try:
        rows = read_rows(args.input)
    except OSError as exc:
        print(f"Could not read input CSV {args.input}: {exc}", file=sys.stderr)
        return 1
    except ValueError as exc:
        print(f"Could not parse input CSV {args.input}: {exc}", file=sys.stderr)
        return 1

    internal_rows = [row for row in rows if is_internal(row, args.L, tolerance)]
    surface_rows = [row for row in rows if is_surface(row, args.L, tolerance)]
    near_edge_rows = [row for row in rows if is_near_edge(row, args.L, tolerance)]

    summaries = [
        summarize("global", rows),
        summarize("internal", internal_rows),
        summarize("surface", surface_rows),
        summarize("near_edge", near_edge_rows),
    ]

    global_summary = summaries[0]
    internal_summary = summaries[1]
    surface_summary = summaries[2]
    near_edge_summary = summaries[3]

    print(f"Input CSV: {args.input}")
    print(f"L: {format_metric(args.L)}")
    print(f"total points: {global_summary['point_count']}")
    print(f"global max abs error: {format_metric(global_summary['max_abs_error'])}")
    print(f"global mean abs error: {format_metric(global_summary['mean_abs_error'])}")
    print(
        "global relative discrete error: "
        f"{format_metric(global_summary['relative_discrete_error'])}"
    )
    print(f"internal points: {internal_summary['point_count']}")
    print(f"internal max abs error: {format_metric(internal_summary['max_abs_error'])}")
    print(f"internal mean abs error: {format_metric(internal_summary['mean_abs_error'])}")
    print(
        "internal relative discrete error: "
        f"{format_metric(internal_summary['relative_discrete_error'])}"
    )
    print(f"surface points: {surface_summary['point_count']}")
    print(f"surface max abs error: {format_metric(surface_summary['max_abs_error'])}")
    print(f"near-edge points: {near_edge_summary['point_count']}")
    print(f"near-edge max abs error: {format_metric(near_edge_summary['max_abs_error'])}")

    try:
        write_summary(args.output, summaries)
    except OSError as exc:
        print(f"Could not write summary CSV {args.output}: {exc}", file=sys.stderr)
        return 1

    print(f"summary CSV: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
